application:
  apiVersion: "0.0.1"

server:
  port: 8086
  shutdown: graceful

spring:
  application:
    name: "products"
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 10s

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true